name: flutter_native_splash

on:
  pull_request:
    paths-ignore:
      - '**.md'
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
      - name: Install Dependencies
        run: flutter pub get
      - name: Format
        run: dart format . --set-exit-if-changed
      - name: Analyze
        run: flutter analyze
      - name: Test
        run: flutter test --test-randomize-ordering-seed random
